name = "bar"
height = 21
autohide = 200
popup_autohide = true

# [[start]]
# type = "workspaces"
# all_monitors = false

# add launcher when it is fixed (right click menu bugs out)
[[start]]
type = "launcher"
show_names = false
show_icons = true
reversed = false

[[end]]
type = "tray"

[[end]]
type = "bluetooth"

[end.format]
not_found = ""
disabled = " Off"
enabled = " On"
connected = " {device_alias}"
connected_battery = " {device_alias} • {device_battery_percent}%"

[end.popup]
scrollable = false

[[end]]
type = "battery"
format = "{percentage}%"

[[end]]
type = "volume"
format = "{icon} {percentage}%"
max_volume = 100
on_scroll_up = "pactl set-sink-volume @DEFAULT_SINK@ +2%"
on_scroll_down = "pactl set-sink-volume @DEFAULT_SINK@ -2%"

[end.icons]
volume_high = "󰕾"
volume_medium = "󰖀"
volume_low = "󰕿"
muted = "󰝟"

[[end]]
type = "clock"
format = " %I:%M %p \n %d/%m/%y"
format_popup = "%r"

